# PyTorch Tensor

In [20]:
import torch

## Tensor Allocation

In [2]:
# 가장 많이쓰인다.
# 32bit
# 2차원 텐서 즉 matrix
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# Int 정수를 담는다
# index를 담을때 많이 쓰인다.
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [21]:
# 0, 1을 담는 텐서
# 현재는 BooleanTensor를 사용
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [22]:
# random한 값으로 3,2 matrix
x = torch.FloatTensor(3, 2)
x

tensor([[ 1.2146e-02,  4.5888e-41],
        [ 7.4643e-02,  4.5888e-41],
        [-9.0489e-08, -2.5250e-29]])

## NumPy Compatibility

In [25]:
import numpy as np

# Define numpy array.
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [26]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [27]:
# torch tensor to numpy
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting

In [29]:
# 같은 타입의 텐서끼리 연산해야 error가 발생안한다.
ft.long()

tensor([[1, 2],
        [3, 4]])

In [32]:
ft.float()

tensor([[1., 2.],
        [3., 4.]])

In [33]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [35]:
# |x| = (3, 2, 2)
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

## Get tensor shape.

In [37]:
# 함수
print(x.size())
# property
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


## Get number of dimensions in the tensor.

In [38]:
print(x.dim())
print(len(x.size()))

3
3


## Get number of elements in certain dimension of the tensor.

In [39]:
print(x.size(1))
print(x.shape[1])

2
2


## Get number of elements in the last dimension.

In [40]:
print(x.size(-1))
print(x.shape[-1])

2
2
