# PyTorch Tensor

In [1]:
import torch

## Tensor Allocation

In [2]:
# 가장 많이쓰인다.
# 32bit
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# Int 정수를 담는다
# index를 담을때 많이 쓰인다.
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [4]:
# 0, 1을 담는 텐서
# BooleanTensor를 사용
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [5]:
x = torch.FloatTensor(3, 2)
x

tensor([[ 0.0000e+00, -3.6893e+19],
        [ 0.0000e+00, -3.6893e+19],
        [ 1.1210e-44,  0.0000e+00]])

## NumPy Compatibility

In [7]:
import numpy as np

# Define numpy array.
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [8]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [9]:
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting

In [14]:
# 같은 타입의 텐서끼리 연산
ft.long()

tensor([[1, 2],
        [3, 4]])

In [12]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [13]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [16]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

## Get tensor shape.

In [17]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


## Get number of dimensions in the tensor.

In [18]:
print(x.dim())
print(len(x.size()))

3
3


## Get number of elements in certain dimension of the tensor.

In [15]:
print(x.size(1))
print(x.shape[1])

2
2


## Get number of elements in the last dimension.

In [16]:
print(x.size(-1))
print(x.shape[-1])

2
2
