##### PyTorch Useful Methods

In [1]:
import torch

### expand: copy the given tensor and concat those at desired dimension.

In [2]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
print(x.size())

torch.Size([2, 1, 2])


In [3]:
# y = x.expand(2,3,2)
y = x.expand(*[2, 3, 2])

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


#### Implement expand with cat.

In [4]:
y = torch.cat([x, x, x], dim=1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### randperm: Random Permutation

In [5]:
# random 순열, index_select랑 같이 쓰면 shuffle
x = torch.randperm(10)

print(x)
print(x.size())

tensor([4, 8, 0, 5, 3, 9, 1, 2, 7, 6])
torch.Size([10])


### argmax: Return index of maximum values

In [6]:
x = torch.randperm(3**3).reshape(3, 3, -1)

print(x)
print(x.size())

tensor([[[11, 15,  3],
         [12,  7,  5],
         [20,  8, 14]],

        [[ 1, 19, 21],
         [16,  6, 25],
         [ 0,  4, 18]],

        [[22,  9, 26],
         [10, 17, 13],
         [23, 24,  2]]])
torch.Size([3, 3, 3])


In [7]:
y = x.argmax(dim=-1)

print(y)
print(y.size())

tensor([[1, 0, 0],
        [2, 2, 2],
        [2, 1, 1]])
torch.Size([3, 3])


### topk: Return tuple of top-k values and indices.

In [8]:
# dim이 살아있다.
values, indices = torch.topk(x, k=1, dim=-1)

print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


Note that topk didn't reduce the dimension, even in $k=1$ case.

In [9]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[15, 12, 20],
        [21, 25, 18],
        [26, 17, 24]])
tensor([[1, 0, 0],
        [2, 2, 2],
        [2, 1, 1]])


In [10]:
print(x.argmax(dim=-1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [11]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

# range로 가져올때만 해당 차원이 살아있다. 인덱스로 가져오면 없어짐
print(x.argmax(dim=-1) == indices[:, :, 0])

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Sort by using topk

In [12]:
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True)

print(values)

tensor([[[15, 11,  3],
         [12,  7,  5],
         [20, 14,  8]],

        [[21, 19,  1],
         [25, 16,  6],
         [18,  4,  0]],

        [[26, 22,  9],
         [17, 13, 10],
         [24, 23,  2]]])


### Topk by using sort

In [13]:
k=1
values, indices = torch.sort(x, dim=-1, descending=True)
values, indices = values[:, :, :k], indices[:, :, :k]

print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[15, 12, 20],
        [21, 25, 18],
        [26, 17, 24]])
tensor([[1, 0, 0],
        [2, 2, 2],
        [2, 1, 1]])


### masked_fill: fill the value if element of mask is True.

In [14]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [15]:
mask = x > 4

print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [16]:
# masked_fill은 mask가 True인 곳에 value값을 채워 넣어라
y = x.masked_fill(mask, value=-1)

print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


### Ones and Zeros

In [17]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [ ]:
# _like : size, type, device도 같은 것을 만든다.
print(torch.ones_like(x))
print(torch.zeros_like(x))