# PyTorch Tensor Operations

In [1]:
import torch

## Arithmetic Element-wise Operations(사칙연산)

In [29]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [30]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [31]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [32]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [33]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [7]:
a == b

tensor([[False,  True],
        [ True, False]])

In [8]:
a != b

tensor([[ True, False],
        [False,  True]])

In [9]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

In [34]:
# pytorch 내부에서 optimize를 잘해서 inplace 계산이 필요 없음
print(a)
print(a.mul(b))
print(a)

# mul_ : a에 그대로 할당
print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [11]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [12]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [38]:
# 첫번째 dimension이 없어짐(첫번째로 짜부)
print(x.sum(dim=0))
# 맨뒤(두번째) dimension이 없어짐
print(x.sum(dim=-1))
# dim은 없어질 dimension

tensor([[1., 2.],
        [4., 8.]])
tensor([[ 3., 12.]])


## Broadcast in Operations

What we did before,

In [39]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [40]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


Broadcast feature provides operations between different shape of tensors.

### Tensor + Scalar

In [41]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [43]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### Tensor + Vector

In [44]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [45]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [46]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [47]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [48]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [49]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


Note that you need to be careful before using broadcast feature.

### Failure Case

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y