# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.2626, 0.4638, 0.3145],
        [0.1725, 0.5353, 0.3530],
        [0.1292, 0.9595, 0.1822]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)

loss

tensor(0.1196, grad_fn=<MseLossBackward>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() # Calculate gradients.

    x = x - learning_rate * x.grad
    
    # You don't need to aware this now.
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 7.2380e-02
tensor([[0.2264, 0.4052, 0.3113],
        [0.2230, 0.5275, 0.4079],
        [0.2560, 0.9241, 0.3417]], requires_grad=True)
2-th Loss: 4.3785e-02
tensor([[0.1983, 0.3596, 0.3088],
        [0.2624, 0.5214, 0.4506],
        [0.3547, 0.8965, 0.4658]], requires_grad=True)
3-th Loss: 2.6487e-02
tensor([[0.1765, 0.3241, 0.3068],
        [0.2929, 0.5166, 0.4838],
        [0.4314, 0.8751, 0.5623]], requires_grad=True)
4-th Loss: 1.6023e-02
tensor([[0.1595, 0.2965, 0.3053],
        [0.3167, 0.5129, 0.5096],
        [0.4911, 0.8584, 0.6373]], requires_grad=True)
5-th Loss: 9.6931e-03
tensor([[0.1463, 0.2751, 0.3041],
        [0.3352, 0.5100, 0.5297],
        [0.5375, 0.8454, 0.6957]], requires_grad=True)
6-th Loss: 5.8637e-03
tensor([[0.1360, 0.2584, 0.3032],
        [0.3496, 0.5078, 0.5453],
        [0.5736, 0.8353, 0.7411]], requires_grad=True)
7-th Loss: 3.5472e-03
tensor([[0.1280, 0.2454, 0.3025],
        [0.3608, 0.5061, 0.5575],
        [0.6017, 0.8275, 0.7764]], requi