# How to use GPU

In [1]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

In [ ]:
x = torch.cuda.FloatTensor(2, 2)

x

In [8]:
x = torch.FloatTensor(2, 2)

x

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
x.cuda()

In [9]:
d = torch.device('cuda:0')

In [ ]:
# cuda 호출 시 복사가 된다.
# 기존 x는 존재 즉 cpu, cuda 할당은 cuda 0에 할당
x.cuda(device=d)

In [12]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()

In [ ]:
x.to(device=d)

## Convert to CPU tensor from CUDA tensor

In [ ]:
x = torch.cuda.FloatTensor(2, 2)

In [14]:
x = x.cpu()

In [15]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU.

In [16]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [17]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.6793, -0.6673],
        [ 0.2191, -0.5865]], requires_grad=True)
Parameter containing:
tensor([-0.6564, -0.0978], requires_grad=True)


In [ ]:
linear = linear.cuda()

print_params(linear)

In [19]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[ 0.6793, -0.6673],
        [ 0.2191, -0.5865]], requires_grad=True)
Parameter containing:
tensor([-0.6564, -0.0978], requires_grad=True)


In [ ]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

Note that nn.Module class does not have 'device' property.  
nn.module은 device property가 없기 때문

In [ ]:
linear.device

## Tricks

In [ ]:
x = torch.cuda.FloatTensor(2, 2)

In [23]:
# new : x와 같은 사이즈와 같은 device의 tensor todtjd
x.new(2, 2)

tensor([[9.0072e+15, 7.3421e+28],
        [6.9790e+22, 1.5218e-42]])

In [24]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]])

In [25]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]])

In [26]:
list(linear.parameters())[0].new(2, 2)

tensor([[7.0065e-45,        nan],
        [1.2603e+14, 4.5902e-41]])